import Image from "next/image";
import Link from "next/link";

import { siteConfig } from "@/config/site";
import { cn } from "@/lib/utils";

/**
 * Intrinsic size of `public/brand/jgs-logo.png`, regenerated by
 * `scripts/build-brand-assets.mjs`. Declared so the browser reserves the right
 * box before the image loads (no layout shift in the sticky header).
 */
const MARK_WIDTH = 360;
const MARK_HEIGHT = 188;

type LogoProps = {
  /** `light` renders for dark backgrounds (footer, hero). */
  tone?: "dark" | "light";
  /** Hides the wordmark, leaving just the mark — for tight bars. */
  markOnly?: boolean;
  /** The site header is above the fold, so its copy should not lazy-load. */
  priority?: boolean;
  className?: string;
};

export function Logo({
  tone = "dark",
  markOnly = false,
  priority = false,
  className,
}: LogoProps) {
  return (
    <Link
      href="/"
      className={cn(
        "group inline-flex items-center gap-2.5 rounded-lg",
        className,
      )}
      aria-label={`${siteConfig.brandName} — beranda`}
    >
      <Image
        src="/brand/jgs-logo.png"
        alt=""
        width={MARK_WIDTH}
        height={MARK_HEIGHT}
        priority={priority}
        /*
         * The artwork carries no text the wordmark does not already provide, so
         * it stays decorative (`alt=""`) and the link is named by aria-label.
         */
        aria-hidden="true"
        className="h-9 w-auto shrink-0 transition-transform duration-200 ease-[var(--ease-out-soft)] group-hover:scale-105 sm:h-10"
      />

      {markOnly ? null : (
        <span className="flex flex-col leading-none">
          <span
            className={cn(
              "text-[15px] font-extrabold tracking-tight",
              tone === "light" ? "text-white" : "text-ink-900",
            )}
          >
            {siteConfig.brandName}
          </span>
          <span
            className={cn(
              "mt-0.5 text-[10px] font-semibold uppercase tracking-[0.16em]",
              tone === "light" ? "text-brand-300" : "text-brand-600",
            )}
          >
            EV Rental
          </span>
        </span>
      )}
    </Link>
  );
}
